### PR TITLE
refactor: simpler and responsive code

### PR DESCRIPTION
**Pull request by sayanee**
simpler code. need to test on mobile if the viewport units `vw` work

### CODE REVIEW

**Comment by sayanee** [comment]
[view port units seems to work on iOS](http://caniuse.com/#search=viewport) so Android should be cool too! 

photo 17-12-14 2 03 02 pm

**Comment by notthetup** [comment]
Hmm.. I was hoping to have the 'ba-dum-tish' nice and big and centered on the screen. And the attribution small and hidden after the fold. What do you think?

**Comment by notthetup** [comment]
I suck at CSS, I have no idea how that can be achieved..

**Comment by sayanee** [comment]
ok made the text bigger to stretch the width of the screen. 

Since it's such a simple page in terms of UI, the attribution can be just below the text but much less emphasised with smaller font and lighter color. Also, having the attribution below the fold will create unnecessary vertical scroll for a simple page.

Merge the PR and see :stuck_out_tongue_closed_eyes:

**Pull request merged**
